language: node_js
node_js: '8'
cache:
  npm: true
script:
  - npx webpack -p
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: OaIJbYUrGYlf1ajgNEOOLIcL2QJ952Q9cdvk0m/vgkyZ5f2HeoNNfqQTQ8L3XejF53aFFK5jS9Afk9KajcxDtgVJjrY7CM3npTAXlrnp4OdSkhAJomp3Y2W471YJootdExVT0Z3M2Uk+ZnbmGsuCwBZvziLLDYk2ffQqeY0M9cX/rAlD1X+BwikfHySqXDDxXHrlCoc7FtMe0mwx43zHj5oJTqbBOAqQ4j6VhXkQIFu738WjkZhhDILrNt56hI9AkV5ScIdGRsP51NFGuNeEiToxq6qZw/VAoeyCdP7Qyh++FTgJO6qnKT1xvfC1oaDYzMTNYAKQZNC3SaSYjdbuior8PKvholWjtfQPRZVzKvqbDS6GwBLzNJjAyNE7ZK+F5O1UTif82DwQU0Cw11UNV8uN+vm4RX7PkHGUy9LG8xUb5KE8wV0zauvodYZ3aUhAZaXnJiCxS137PIG8VecPb3v8stLgMJhVo7NwmICFTDi6LWLzKNrsFBSswsEczl5nkdJ3+Jax6pJaI2phWMT7moIgDERB9SwYp2bH39PWE/hwiK6fTH1o/3p9hJsDE+x+/bw233RohcCHYwX8bnWi2vXHD08nsr/99lQjhO+wutP/oXKgOqnUlmfEE54/kRuaaCAMbZisAWj802aMzEQp6fdclYOdmnrn1O8O+tk70Pk=
  - secure: k6ZHfaGYGZVRUkY4ivNXH/22PE8lCV16xnxV9SJEf3gBi25Eo7zkxfkUA3qt7ITqiAc/94mYsb2fH1qQwMWiF4jMLa8FDnyTd+yaiziy+nWjSi1U0WIGdh0bUbtKr2GOFOWkL1RAI9GpFm6oFGZ6mJMTvuZdt2lrODXeeb5Ntzt1bnc6CEeeCdLvqbpeh0xP5ycjBZYH5/8JFitI97x7rAWdBpXpbuJRbeSRjuDv2ZIg8oxh0NnETvIW/CbnX+nQt4ySrAxoL9m120M41SVFw+fdRU3q1DlrIndY+kYu/eeE0Nfp/c4FwJN3bbIiR7vLgzDZTMxMTnJ+69Axa8mjz2x6PeRrm+dtXAlml87iG4/IwgrSI5akCutZ0Hhsfqp0fotSH6KC2LE9J7zgg6kH2iU8HKbatpdSQbMgGBcOO7VVe9HeVKdaZtQo78CBmQT8KVWRmF5VB2o7uEuwfvZHMa6cmKsexg7+2iYneF6lqEOZ30zyc3tNW/WX1YCJf2KX0Giv0zMeEq/3r7yYY4W5HYZfu9lPI+Nfh+6t/AllJjB7MzPW7sfyPgtU5xHMPgVy1vKYtKbiiae+ScGnzovWdw02GdkIAfYBlaoI/ho6i6jOQURjj+wBugagX2/9OL9Z4gY04kPpsNuy8LQDM/g997KAoV7p8QeP//NQUUo2LvQ=
